language: php

php:
  - 5.6

install:
  - sudo pip install codecov

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp .env.travis .env
  - mysql -e 'create database homestead;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate:rollback

script:
  - php artisan migrate:refresh
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - php artisan migrate:refresh --seed

services:
  - postgresql

after_success:
  - bash <(curl -s https://codecov.io/bash)
